/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacob_jacobgen_TypeLibInspector */

#ifndef _Included_com_jacob_jacobgen_TypeLibInspector
#define _Included_com_jacob_jacobgen_TypeLibInspector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacob_jacobgen_TypeLibInspector
 * Method:    queryInterface
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jacob_jacobgen_TypeLibInspector_queryInterface
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
