/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacob_com_ComThread */

#ifndef _Included_com_jacob_com_ComThread
#define _Included_com_jacob_com_ComThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacob_com_ComThread
 * Method:    doCoInitialize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jacob_com_ComThread_doCoInitialize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jacob_com_ComThread
 * Method:    doCoUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jacob_com_ComThread_doCoUninitialize
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
