/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DispatchEvents */

#ifndef _Included_DispatchEvents
#define _Included_DispatchEvents
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DispatchEvents
 * Method:    init
 * Signature: (LDispatch;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_jacob_com_DispatchEvents_init
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     DispatchEvents
 * Method:    init2
 * Signature: (LDispatch;Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jacob_com_DispatchEvents_init2
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     DispatchEvents
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jacob_com_DispatchEvents_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif


