/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacob_com_DispatchProxy */

#ifndef _Included_com_jacob_com_DispatchProxy
#define _Included_com_jacob_com_DispatchProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacob_com_DispatchProxy
 * Method:    MarshalIntoStream
 * Signature: (Lcom/jacob/com/Dispatch;)V
 */
JNIEXPORT void JNICALL Java_com_jacob_com_DispatchProxy_MarshalIntoStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jacob_com_DispatchProxy
 * Method:    MarshalFromStream
 * Signature: ()Lcom/jacob/com/Dispatch;
 */
JNIEXPORT jobject JNICALL Java_com_jacob_com_DispatchProxy_MarshalFromStream
  (JNIEnv *, jobject);

/*
 * Class:     com_jacob_com_DispatchProxy
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jacob_com_DispatchProxy_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
