/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class STA */

#ifndef _Included_com_jacob_com_STA
#define _Included_com_jacob_com_STA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacob_com_STA
 * Method:    doMessagePump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jacob_com_STA_doMessagePump
  (JNIEnv *, jobject);

/*
 * Class:     com_jacob_com_STA
 * Method:    quitMessagePump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jacob_com_STA_quitMessagePump
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
